[program:sveltekit]
command=/usr/bin/npm run start
directory=/usr/local/bin/pifire/pifire.app
autostart=true
autorestart=true
startretries=3
stderr_logfile=/usr/local/bin/pifire/logs/sveltekit.err.log
stdout_logfile=/usr/local/bin/pifire/logs/sveltekit.out.log
user= root